### ISSUE TITLE
No enum constant com.github.kokorin.jaffree.StreamType.VİDEO

### ISSUE THREAD

**Issue by tarikkilic** [kokorin/Jaffree#101]
I think getCodecType() method works between Windows and Linux  differently.

Jaffre Debug Mod Logs:

> 2020-11-03 | 14:52:15.434 | http-nio-8090-exec-2 |  INFO | c.g.k.j.p.ProcessHandler | Command constructed:
ffprobe -loglevel 16 -show_streams -show_private_data -probesize 32 -analyzeduration 0 -print_format flat -i /var/www/contents/rawVideo/h264_sintel_1080p.mp4
2020-11-03 | 14:52:15.435 | http-nio-8090-exec-2 |  INFO | c.g.k.j.p.ProcessHandler | Starting process: ffprobe
2020-11-03 | 14:52:15.440 | http-nio-8090-exec-2 | DEBUG | c.g.k.j.p.ProcessHandler | Starting IO interaction with process
2020-11-03 | 14:52:15.441 | StdErr | DEBUG | c.g.k.j.process.Executor | StdErr thread has started
2020-11-03 | 14:52:15.441 | http-nio-8090-exec-2 |  INFO | c.g.k.j.p.ProcessHandler | Waiting for process to finish
2020-11-03 | 14:52:15.441 | StdOut | DEBUG | c.g.k.j.process.Executor | StdOut thread has started
2020-11-03 | 14:52:15.525 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.index = 0
2020-11-03 | 14:52:15.525 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.codec_name = "h264"
2020-11-03 | 14:52:15.525 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.codec_long_name = "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10"
2020-11-03 | 14:52:15.525 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.profile = "High"
**2020-11-03 | 14:52:15.526 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.codec_type = "video"**
2020-11-03 | 14:52:15.526 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.codec_time_base = "1/48"
2020-11-03 | 14:52:15.526 | StdErr | DEBUG | c.g.k.j.process.Executor | StdErr thread has finished
2020-11-03 | 14:52:15.526 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.codec_tag_string = "avc1"
2020-11-03 | 14:52:15.526 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.codec_tag = "0x31637661"
2020-11-03 | 14:52:15.526 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.width = 1920
2020-11-03 | 14:52:15.526 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.height = 1080
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.coded_width = 1920
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.coded_height = 1088
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.closed_captions = 0
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.has_b_frames = 2
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.sample_aspect_ratio = "N/A"
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.display_aspect_ratio = "N/A"
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.pix_fmt = "yuv420p"
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.level = 50
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.color_range = "unknown"
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.color_space = "unknown"
2020-11-03 | 14:52:15.527 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.color_transfer = "unknown"
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.color_primaries = "unknown"
2020-11-03 | 14:52:15.528 | http-nio-8090-exec-2 |  INFO | c.g.k.j.p.ProcessHandler | Process has finished with status: 0
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.chroma_location = "left"
2020-11-03 | 14:52:15.528 | http-nio-8090-exec-2 | DEBUG | c.g.k.j.p.ProcessHandler | Waiting for Executor to stop
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.field_order = "unknown"
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.timecode = "N/A"
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.refs = 1
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.is_avc = "true"
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.nal_length_size = "4"
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.id = "N/A"
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.r_frame_rate = "24/1"
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.avg_frame_rate = "24/1"
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.time_base = "1/24"
2020-11-03 | 14:52:15.528 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.start_pts = 0
2020-11-03 | 14:52:15.529 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.start_time = "0.000000"
2020-11-03 | 14:52:15.529 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.duration_ts = 1253
2020-11-03 | 14:52:15.529 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.duration = "52.208333"
2020-11-03 | 14:52:15.529 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.bit_rate = "2108423"
2020-11-03 | 14:52:15.529 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.max_bit_rate = "N/A"
2020-11-03 | 14:52:15.529 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.bits_per_raw_sample = "8"
2020-11-03 | 14:52:15.529 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.nb_frames = "1253"
2020-11-03 | 14:52:15.530 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.nb_read_frames = "N/A"
2020-11-03 | 14:52:15.530 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.nb_read_packets = "N/A"
2020-11-03 | 14:52:15.531 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.default = 1
2020-11-03 | 14:52:15.531 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.dub = 0
2020-11-03 | 14:52:15.531 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.original = 0
2020-11-03 | 14:52:15.531 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.comment = 0
2020-11-03 | 14:52:15.531 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.lyrics = 0
2020-11-03 | 14:52:15.531 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.karaoke = 0
2020-11-03 | 14:52:15.531 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.forced = 0
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.hearing_impaired = 0
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.visual_impaired = 0
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.clean_effects = 0
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.attached_pic = 0
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.disposition.timed_thumbnails = 0
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.tags.creation_time = "1970-01-01T00:00:00.000000Z"
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.tags.language = "und"
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.0.tags.handler_name = "VideoHandler"
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.index = 1
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.codec_name = "aac"
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.codec_long_name = "AAC (Advanced Audio Coding)"
2020-11-03 | 14:52:15.532 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.profile = "unknown"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.codec_type = "audio"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.codec_time_base = "1/48000"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.codec_tag_string = "mp4a"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.codec_tag = "0x6134706d"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.sample_fmt = "fltp"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.sample_rate = "48000"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.channels = 2
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.channel_layout = "stereo"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.bits_per_sample = 0
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.id = "N/A"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.r_frame_rate = "0/0"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.avg_frame_rate = "0/0"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.time_base = "1/48000"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.start_pts = 0
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.start_time = "0.000000"
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.duration_ts = 2506032
2020-11-03 | 14:52:15.533 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.duration = "52.209000"
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.bit_rate = "126694"
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.max_bit_rate = "128000"
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.bits_per_raw_sample = "N/A"
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.nb_frames = "2435"
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.nb_read_frames = "N/A"
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.nb_read_packets = "N/A"
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.default = 1
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.dub = 0
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.original = 0
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.comment = 0
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.lyrics = 0
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.karaoke = 0
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.forced = 0
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.hearing_impaired = 0
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.visual_impaired = 0
2020-11-03 | 14:52:15.534 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.clean_effects = 0
2020-11-03 | 14:52:15.535 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.attached_pic = 0
2020-11-03 | 14:52:15.535 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.disposition.timed_thumbnails = 0
2020-11-03 | 14:52:15.535 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.tags.creation_time = "1970-01-01T00:00:00.000000Z"
2020-11-03 | 14:52:15.535 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.tags.language = "und"
2020-11-03 | 14:52:15.535 | StdOut | DEBUG | c.g.k.j.f.d.FlatFormatParser | Parsed: streams.stream.1.tags.handler_name = "SoundHandler"
2020-11-03 | 14:52:15.536 | StdOut | DEBUG | c.g.k.j.process.Executor | StdOut thread has finished
2020-11-03 | 14:52:15.637 | http-nio-8090-exec-2 | DEBUG | c.g.k.j.process.Executor | Stopping execution
2020-11-03 | 14:52:15.640 | http-nio-8090-exec-2 |  WARN | c.g.k.j.f.data.DBase | Failed to parse StreamType: video
java.lang.IllegalArgumentException: No enum constant com.github.kokorin.jaffree.StreamType.VİDEO
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.github.kokorin.jaffree.StreamType.valueOf(StreamType.java:20)
	at com.github.kokorin.jaffree.ffprobe.data.DBase$4.convert(DBase.java:161)
	at com.github.kokorin.jaffree.ffprobe.data.DBase$4.convert(DBase.java:153)
	at com.github.kokorin.jaffree.ffprobe.data.DBase.getValue(DBase.java:44)
	at com.github.kokorin.jaffree.ffprobe.data.DBase.getStreamType(DBase.java:78)
	at com.github.kokorin.jaffree.ffprobe.Stream.getCodecType(Stream.java:77)
	at com.saattek.atlasliveencoder.ffmpeg.FFprobeA.getInfoFromContent(FFprobeA.java:67)
	at com.saattek.atlasliveencoder.controller.InputController.getStreamInfo(InputController.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.saattek.atlasliveencoder.config.CorsFilter.doFilter(CorsFilter.java:28)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

My Jaffree Code execute statement:
`        FFprobeResult result = null;
        try {
            ffprobe
                    .setShowStreams(true)
                    .setInput(inputStreamDto.getStreamPath());
            if(inputStreamDto.getInputType() == InputType.UDP){
                logger.debug("getInfoFromContent | into UDP block");
                result = ffprobe
                        .addArguments("-timeout","10000000")
                        .execute();
            }
            else if(inputStreamDto.getInputType() == InputType.FILE){
                logger.debug("getInfoFromContent | into FILE block");
                result = ffprobe
                        .execute();
            }`

When I want to get codec type:
`        for (Stream stream : result.getStreams()) {
            StreamInfoDto streamInfoDto = new StreamInfoDto();
            streamInfoDto.setBitrate(stream.getBitRate());
            streamInfoDto.setCodecType(stream.getCodecType().name());`

I run same ffmpeg command in windows. I got codec_type. Also when i run debug mode, i can see 'codec_type' in section.It's exist.

> streams.stream.0.codec_type="video"

But If I build and run in centos 7, It's work. I got codec_type like "VIDEO".

**Comment by kokorin** [comment]
It's very strange. 

Could you provide `ffprobe` output for the same command you execute but without Jaffree usage?
`ffprobe -loglevel 16 -show_streams -show_private_data -probesize 32 -analyzeduration 0 -print_format flat -i /var/www/contents/rawVideo/h264_sintel_1080p.mp4`

Jaffree is tested with Github actions on iOS, Windows & Linux. So it's unlikely that the problem is in Jaffree.

Also it would be greate if you provide a project demonstrating the problem.

**Comment by tarikkilic** [comment]
> streams.stream.0.index=0
streams.stream.0.codec_name="h264"
streams.stream.0.codec_long_name="H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10"
streams.stream.0.profile="High"
streams.stream.0.codec_type="video"
streams.stream.0.codec_time_base="1/48"
streams.stream.0.codec_tag_string="avc1"
streams.stream.0.codec_tag="0x31637661"
streams.stream.0.width=1920
streams.stream.0.height=1080
streams.stream.0.coded_width=1920
streams.stream.0.coded_height=1088
streams.stream.0.closed_captions=0
streams.stream.0.has_b_frames=2
streams.stream.0.sample_aspect_ratio="N/A"
streams.stream.0.display_aspect_ratio="N/A"
streams.stream.0.pix_fmt="yuv420p"
streams.stream.0.level=50
streams.stream.0.color_range="unknown"
streams.stream.0.color_space="unknown"
streams.stream.0.color_transfer="unknown"
streams.stream.0.color_primaries="unknown"
streams.stream.0.chroma_location="left"
streams.stream.0.field_order="unknown"
streams.stream.0.timecode="N/A"
streams.stream.0.refs=1
streams.stream.0.is_avc="true"
streams.stream.0.nal_length_size="4"
streams.stream.0.id="N/A"
streams.stream.0.r_frame_rate="24/1"
streams.stream.0.avg_frame_rate="24/1"
streams.stream.0.time_base="1/24"
streams.stream.0.start_pts=0
streams.stream.0.start_time="0.000000"
streams.stream.0.duration_ts=1253
streams.stream.0.duration="52.208333"
streams.stream.0.bit_rate="2108423"
streams.stream.0.max_bit_rate="N/A"
streams.stream.0.bits_per_raw_sample="8"
streams.stream.0.nb_frames="1253"
streams.stream.0.nb_read_frames="N/A"
streams.stream.0.nb_read_packets="N/A"
streams.stream.0.disposition.default=1
streams.stream.0.disposition.dub=0
streams.stream.0.disposition.original=0
streams.stream.0.disposition.comment=0
streams.stream.0.disposition.lyrics=0
streams.stream.0.disposition.karaoke=0
streams.stream.0.disposition.forced=0
streams.stream.0.disposition.hearing_impaired=0
streams.stream.0.disposition.visual_impaired=0
streams.stream.0.disposition.clean_effects=0
streams.stream.0.disposition.attached_pic=0
streams.stream.0.disposition.timed_thumbnails=0
streams.stream.0.tags.creation_time="1970-01-01T00:00:00.000000Z"
streams.stream.0.tags.language="und"
streams.stream.0.tags.handler_name="VideoHandler"
streams.stream.1.index=1
streams.stream.1.codec_name="aac"
streams.stream.1.codec_long_name="AAC (Advanced Audio Coding)"
streams.stream.1.profile="unknown"
streams.stream.1.codec_type="audio"
streams.stream.1.codec_time_base="1/48000"
streams.stream.1.codec_tag_string="mp4a"
streams.stream.1.codec_tag="0x6134706d"
streams.stream.1.sample_fmt="fltp"
streams.stream.1.sample_rate="48000"
streams.stream.1.channels=2
streams.stream.1.channel_layout="stereo"
streams.stream.1.bits_per_sample=0
streams.stream.1.id="N/A"
streams.stream.1.r_frame_rate="0/0"
streams.stream.1.avg_frame_rate="0/0"
streams.stream.1.time_base="1/48000"
streams.stream.1.start_pts=0
streams.stream.1.start_time="0.000000"
streams.stream.1.duration_ts=2506032
streams.stream.1.duration="52.209000"
streams.stream.1.bit_rate="126694"
streams.stream.1.max_bit_rate="128000"
streams.stream.1.bits_per_raw_sample="N/A"
streams.stream.1.nb_frames="2435"
streams.stream.1.nb_read_frames="N/A"
streams.stream.1.nb_read_packets="N/A"
streams.stream.1.disposition.default=1
streams.stream.1.disposition.dub=0
streams.stream.1.disposition.original=0
streams.stream.1.disposition.comment=0
streams.stream.1.disposition.lyrics=0
streams.stream.1.disposition.karaoke=0
streams.stream.1.disposition.forced=0
streams.stream.1.disposition.hearing_impaired=0
streams.stream.1.disposition.visual_impaired=0
streams.stream.1.disposition.clean_effects=0
streams.stream.1.disposition.attached_pic=0
streams.stream.1.disposition.timed_thumbnails=0
streams.stream.1.tags.creation_time="1970-01-01T00:00:00.000000Z"
streams.stream.1.tags.language="und"
streams.stream.1.tags.handler_name="SoundHandler"

Its work, thank you. 
`String codecType = stream.getSection().getString("codec_type");`

Not today, may be i will provide tomorrow.

Because, I am showing streams and some metadata.  I must specify video, audio or data. Maybe  one multicast has several video, audio.
