### ISSUE TITLE
How to move Moov atom to the front in an mp4

### ISSUE THREAD

**Issue by waterdrake** [kokorin/Jaffree#141]
I have this command that I use with ffmpeg on the terminal to move the moov atom to the front of an mp4:

`ffmpeg -i inputvidfile.mp4 -vcodec copy -acodec copy -movflags faststart outputvidfile.mp4
`

How can I do that with Jaffree?

**Comment by kokorin** [comment]
Hello, use FFmpeg#addArguments, will add it to examples soon.

**Comment by waterdrake** [comment]
@kokorin Thanks you! Yes an example would help tremendously. I am new to ffmpeg.

**Comment by waterdrake** [comment]
I tried doing this as per your comment:

```
SeekableByteChannel outputChannel = Files.newByteChannel(path);
final AtomicLong duration = new AtomicLong();
                FFmpeg.atPath()
                        .addInput(PipeInput.pumpFrom(inputStream))
                        .setOverwriteOutput(true)
                        .addArguments("-vcodec", "copy")
                        .addArguments("-acodec", "copy")
                        .addArguments("-movflags", "faststart")
                        .addOutput(ChannelOutput.toChannel(path.getFileName().toString(), outputChannel))
                        .setProgressListener(new ProgressListener() {
                            @Override
                            public void onProgress(FFmpegProgress progress) {
                                double percents = 100. * progress.getTimeMillis() / duration.get();
                            }
                        })
                        .execute();

```

But I got this error:
```
com.github.kokorin.jaffree.JaffreeException: Failed to start process.
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:99)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:335)
...
Caused by: java.io.IOException: Cannot run program "ffmpeg": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:92)
	... 36 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
```

It looks like it thinks ffmpeg does not exist. This is odd because everything compiles when I added your library. I am trying to run this from the google cloud.

Any clue what may be happening?

**Comment by kokorin** [comment]
> Cannot run program "ffmpeg": error=2, No such file or directory

Make sure ffmpeg is added to PATH env variable, or you can specify it explicitly with `FFmpeg.atPath("/path/to/directory")`

Also I noticed you added per-output arguments as global arguments. I recommend refactoring to:
```java
ChannelOutput.toChannel(path.getFileName().toString(), outputChannel)
                        .addArguments("-vcodec", "copy")
                        .addArguments("-acodec", "copy")
                        .addArguments("-movflags", "faststart")
``` 

or even better:
```java
ChannelOutput.toChannel(path.getFileName().toString(), outputChannel)
                        .copyAllCodecs()
                        .addArguments("-movflags", "faststart")
```

**Comment by waterdrake** [comment]
That works. Is there a way to have ffmpeg build as a maven dependency? The unix ffmpeg file is kind of big to include with my web app project.

**Comment by kokorin** [comment]
You can use maven-antrun-plugin for example to download ffmpeg static build from somewhere. 
Personally I would prefer building Docker image based on one of the many ffmpeg Docker images.

**Comment by waterdrake** [comment]
Any recommendations on where to get that static build from?

**Comment by kokorin** [comment]
I would start with https://ffmpeg.org/download.html
