### ISSUE TITLE
Need Help Extracting libvorbis Audio from an MP4 File

### ISSUE THREAD

**Issue by PulseBeat02** [kokorin/Jaffree#186]
Hello! I am relatively new to the API, so I am not entirely sure how to solve this specific issue. The task I am trying to do is pretty simple - I am trying to extract an OGG (libvorbis) audio file out of an MP4 video file that has been provided.

From the example, I tried executing this code:
```java
  public static void tryExtraction() {

    final Path parent = Paths.get(System.getProperty("user.dir"));
    final Path path = parent.resolve("ffmpeg-test");
    final Path audioPath = parent.resolve("audio.ogg");

    try {
      final PipeOutput output = PipeOutput.pumpTo(Files.newOutputStream(audioPath));
      output.setCodec(StreamType.AUDIO, "libvorbis");
      output.addArguments("-b:v", "160K");
      output.addArguments("-ac", "2");
      output.addArguments("-r", "44100");
      output.addArguments("-filter:a", "\"volume=2\"");
      new FFmpeg(
              Paths.get(
                  "/Users/bli24/IdeaProjects/MinecraftMediaLibrary/ffmpeg-test/ffmpeg/ffmpeg-x86_64-osx"))
          .addInput(UrlInput.fromPath(Paths.get("/Users/bli24/Downloads/kda.mp4")))
          .addOutput(output)
          .execute();
    } catch (final IOException e) {
      e.printStackTrace();
    }
    
  }
  ```
  
From the arguments, it should extract the libvorbis file with the specified attributes (volume, bitrate, etc), however, I seem to be getting this odd error:

```java
Exception in thread "main" com.github.kokorin.jaffree.JaffreeException: Failed to execute, was interrupted
	at com.github.kokorin.jaffree.process.ProcessHandler.interactWithProcess(ProcessHandler.java:189)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:146)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:358)
	at io.github.pulsebeat02.minecraftmedialibrary.ffmpeg.FFmpegAudioTest.tryExtraction(FFmpegAudioTest.java:88)
	at io.github.pulsebeat02.minecraftmedialibrary.ffmpeg.FFmpegAudioTest.main(FFmpegAudioTest.java:60)
	Suppressed: com.github.kokorin.jaffree.JaffreeException: ffmpeg exited with message: [NULL @ 0x7fa2e380f400] [error] Unable to find a suitable output format for 'tcp://127.0.0.1:53003'
[error] tcp://127.0.0.1:53003: Invalid argument
		at com.github.kokorin.jaffree.ffmpeg.FFmpegResultReader.read(FFmpegResultReader.java:136)
		at com.github.kokorin.jaffree.ffmpeg.FFmpegResultReader.read(FFmpegResultReader.java:38)
		at com.github.kokorin.jaffree.process.ProcessHandler$1.run(ProcessHandler.java:233)
		at com.github.kokorin.jaffree.process.Executor$1.run(Executor.java:83)
		at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.github.kokorin.jaffree.process.ProcessHandler.waitForExecutorToStop(ProcessHandler.java:318)
	at com.github.kokorin.jaffree.process.ProcessHandler.interactWithProcess(ProcessHandler.java:182)
Caused by: java.lang.InterruptedException: sleep interrupted

	... 4 more
```

I am not sure why I would be getting this error, but I think perhaps it has something to do with the `UrlInput`. I made sure that all my paths are valid and even made sure the FFmpeg binary is correct. Does anyone know perhaps where I went wrong in my code?

**Comment by kokorin** [comment]
Hello, you don't need PipeOutput, use UrlOutput. Also you mixed library name and codec name. You need to set off codec. Or even simpler you can specify output file with ogg extension, FFmpeg will automatically detect codec required.

**Comment by PulseBeat02** [comment]
I see. Changing to this code seemed to make the error go away. Just to make sure, would this code be correct?
```java
    final Path parent = Paths.get(System.getProperty("user.dir"));
    final Path path = parent.resolve("ffmpeg-test");
    final Path audioPath = path.resolve("audio.ogg");
    if (Files.notExists(path)) {
      try {
        Files.createDirectory(path);
      } catch (final IOException e) {
        e.printStackTrace();
      }
    }

    final UrlOutput output = UrlOutput.toPath(audioPath);
    output.addArguments("-b:v", "160K");
    output.addArguments("-ac", "2");
    output.addArguments("-r", "44100");
    output.addArguments("-filter:a", "\"volume=1\"");

    new FFmpeg(
            Paths.get(
                "/Users/bli24/IdeaProjects/MinecraftMediaLibrary/ffmpeg-test/ffmpeg/ffmpeg-x86_64-osx"))
        .addInput(UrlInput.fromPath(Paths.get("/Users/bli24/Downloads/kda.mp4")))
        .addOutput(output)
        .execute();
        ```

**Comment by kokorin** [comment]
Yes, it is. One notice: no need to escape arguments you can pass just "volume=1"
