### ISSUE TITLE
ArrayIndexOutOfBoundsException in NutReader.readToFrame()

### ISSUE THREAD

**Issue by marklassau** [kokorin/Jaffree#195]
```
	Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
		at com.github.kokorin.jaffree.nut.NutReader.readToFrame(NutReader.java:126)
		at com.github.kokorin.jaffree.nut.NutReader.getMainHeader(NutReader.java:57)
		at com.github.kokorin.jaffree.ffmpeg.NutFrameReader.read(NutFrameReader.java:68)
		at com.github.kokorin.jaffree.ffmpeg.FrameOutput$FrameOutputNegotiator.negotiate(FrameOutput.java:215)
		at com.github.kokorin.jaffree.net.NegotiatingTcpServer.serve(NegotiatingTcpServer.java:44)
		at com.github.kokorin.jaffree.net.TcpServer.run(TcpServer.java:66)
```

Code looks like this:
```
for (int i = 0; i < mainHeader.timeBases.length; i++) {
    lastPts[i] = Util.convertTimestamp(pts, ptsTimebase, mainHeader.timeBases[i]);
}
```
It will throw ArrayIndexOutOfBoundsException when `mainHeader.timeBases` array is longer than the `lastPts` array.

This seems to be uncommon, but I have experienced in one customer file.
The video was a Zoom recording and contains 3 streams: Audio, Video and Menu.

When I trace the `readMainHeader()` call I can see the NUT header reports streamCount = 2 but timeBaseCount = 3.

**Comment by marklassau** [comment]
Unfortunately this is a customer's file and is over an hour in length.
It is likely "commercial in confidence": I can ask the customer, but I don't think they will let me share it :(

I could share metadata like `mediainfo` output or `ffprobe`.

This one file is the only time I have seen this.
But the cause is pretty obvious.
If `timeBaseCount` > `streamCount` then the `ArrayIndexOutOfBoundsException` has to happen with current code.

I wrote a quick patch that was able to make Jaffree work on the problem file:

```
final int commonLength = Math.min(mainHeader.timeBases.length, lastPts.length);
for (int i = 0; i < commonLength; i++) {
    ...
}
```

I was planning on raising that as a PR.

**Comment by marklassau** [comment]
This is the output of `mediainfo`:

```
General
Complete name                            : GMT20210727-080013_Recording_1920x1050.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 149 MiB
Duration                                 : 59 min 22 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 350 kb/s
Encoded date                             : UTC 2021-07-27 08:00:13
Tagged date                              : UTC 2021-07-27 08:00:13

Video
ID                                       : 2
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5
Format settings                          : CABAC / 11 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 11 frames
Muxing mode                              : Container profile=High@3.1
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 59 min 22 s
Bit rate                                 : 222 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 050 pixels
Display aspect ratio                     : 1.85:1
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.004
Stream size                              : 94.3 MiB (63%)
Title                                    : H.264/AVC video
Encoded date                             : UTC 2021-07-27 08:00:13
Tagged date                              : UTC 2021-07-27 08:00:13
Codec configuration box                  : avcC

Audio
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 59 min 22 s
Bit rate mode                            : Variable
Bit rate                                 : 126 kb/s
Maximum bit rate                         : 160 kb/s
Channel(s)                               : 1 channel
Channel layout                           : C
Sampling rate                            : 32.0 kHz
Frame rate                               : 31.250 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 53.6 MiB (36%)
Title                                    : AAC audio
Encoded date                             : UTC 2021-07-27 08:00:13
Tagged date                              : UTC 2021-07-27 08:00:13
Menus                                    : 3

Menu
ID                                       : 3
Codec ID                                 : text
Duration                                 : 59 min 22 s
Title                                    : Text
Encoded date                             : UTC 2021-07-27 08:00:13
Tagged date                              : UTC 2021-07-27 08:00:13
Menu For                                 : 1
Duration_FirstFrame                      : 3500160
00:00:00.000                             : Sharing Started
00:58:51.160                             : Sharing Stopped
```

**Comment by kokorin** [comment]
@marklassau despite your solution with `Math.min` works, it is only correct if audio and video streams come before any "extra" stream. In case if streams are Extra, Video, Audio - all PTS on syncpoint will be corrupted.

Probably a fix should iterate not over timebases, but over streams since `lastPts` contains values on per-stream basis: 

```lastPts = new long[mainHeader.streamCount]```

After very quick check, the following seems to solve the problem:

```java
for (int i = 0; i < mainHeader.streamCount; i++) {
    Rational streamTimeBase = mainHeader.timeBases[streamHeaders[i].timeBaseId];
    lastPts[i] = Util.convertTimestamp(pts, ptsTimebase, streamTimeBase);
}
```

**Comment by marklassau** [comment]
> despite your solution with Math.min works, it is only correct if audio and video streams come before any "extra" stream.

Understood - I just got lucky ;)

Your new code makes a lot more sense given that the stream count might be different to the timebase count - you have to look up the timeBaseId for each stream to map them correctly.

I will update my fork to use your code instead of my hack.
And I look forward to a mainstream release with a bug fix so we can get off the forked version back onto a mainstream release.

Thanks for your fast reply - and thanks for an awesome library!

**Comment by kokorin** [comment]
Please, pay attention that in a PR sample file showing the error should either present, or be generated with `Artifacts`.

**Comment by marklassau** [comment]
The only file I have seen cause this problem is 150 MiB - even if I could get permission to share it I don't think you will want to put it in your repo.

I am happy to try and replicate using `Artifacts` ... but not sure how that will go.
I am still fairly new to `Jaffree` and `ffmpeg` in general.
The trick is we will have to try and produce an extra stream that has a timebase but does not add to the streamCount.

Any hints?

**Comment by marklassau** [comment]
Actually - looks like I can replicate this bug with an existing file from Artifacts : `3chapters_180s.mkv`

**Comment by marklassau** [comment]
Pull Request:
https://github.com/kokorin/Jaffree/pull/197

**Comment by kokorin** [comment]
Fixed
