### ISSUE TITLE
How to use push streaming

### ISSUE THREAD

**Issue by cayden** [kokorin/Jaffree#206]
How to use push streaming? Are there any examples, thank you!

**Comment by kokorin** [comment]
How would you do that with ffmpeg comand line? thank you too!

**Comment by cayden** [comment]
@kokorin hi, for example
` ffmpeg -f avfoundation -i "1" -vcodec libx264 -preset ultrafast -f h264 -r 30 -f flv  "rtmp://xxxxxxxxxxxxxxx" `

**Comment by cayden** [comment]
I wrote it like this, but it was wrong！
`     
 final AtomicReference<FFmpegResult> result = new AtomicReference<>();
        final FFmpeg ffmpeg = FFmpeg.atPath(BIN)
                .addInput(UrlInput.fromUrl("avfoundation")
                        .setCodec(StreamType.VIDEO,"libx264")
                        .setFrameRate(30))
                .addOutput(UrlOutput.toUrl("rtmp://22888.livepush.myqcloud.com/live/test?txSecret=622345cf14d61381958ef6fae046c240&txTime=611621A3"));

        final AtomicReference<Exception> executeException = new AtomicReference<>();
        Thread thread = new Thread() {
            @Override
            public void run() {
                try {
                    FFmpegResult r = ffmpeg.execute();
                    result.set(r);
                } catch (Exception e) {
                    executeException.set(e);
                }
            }
        };
        thread.start();
`

**Comment by kokorin** [comment]
It's very interesting! Could you tell me what "it" was wrong? Do you have any logs?
It looks like you are trying to capture a screen. Check `CaptureInput` and its subclasses.

**Comment by cayden** [comment]
@kokorin 
Yes, I need to record the screen and push the stream. Is there an example? thanks!
`  
final AtomicReference<FFmpegResult> result = new AtomicReference<>();
        final FFmpeg ffmpeg = FFmpeg.atPath(BIN)
                .addInput(CaptureInput.MacOsAvFoundation.captureDesktop()
                        .setCodec(StreamType.VIDEO,"libx264")
                        .setFrameRate(30))
                .addOutput(UrlOutput.toUrl("rtmp://xxxxx")); 
`

**Comment by kokorin** [comment]
Again: do you have any logs? Please, value not only your time.

**Comment by cayden** [comment]
The log is as follows
`
        ffmpeg/ffmpeg -loglevel level+info -f avfoundation -r 10 -i 1 -i default:none -y -t 10.000 /Users/cayden/Documents/desktop.mp4
05:50:52.888 [main] INFO  c.g.k.j.p.ProcessHandler - Starting process: ffmpeg/ffmpeg
 com.github.kokorin.jaffree.JaffreeException: Failed to start process.
  	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:148)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:400)
	at com.github.kokorin.jaffree.ffmpeg.FFmpegTest.testDesktopCapture(FFmpegTest.java:877)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.io.IOException: Cannot run program "ffmpeg/ffmpeg": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:141)
	... 29 more
Caused by: java.io.IOException: error=2, No such file or directory`

**Comment by kokorin** [comment]
Check how you build command line, it contains 2 inputs: 
1. `-f avfoundation -r 10 -i 1`
2.  `-i default:none` 

Probably you added 2 inputs or added global arguments. Show code snippet, how do you create and execute Jaffree.
