### ISSUE TITLE
NumberFormatException For input string: "N/A" 

### ISSUE THREAD

**Issue by msly** [kokorin/Jaffree#35]
`java.lang.NumberFormatException: For input string: "N/A"
	at com.github.kokorin.jaffree.Rational.valueOf(Rational.java:165)
	at com.github.kokorin.jaffree.ffprobe.data.DBase$RationalConverter.convert(DBase.java:158)
	at com.github.kokorin.jaffree.ffprobe.data.DBase$RationalConverter.convert(DBase.java:140)
	at com.github.kokorin.jaffree.ffprobe.data.DBase.getValue(DBase.java:44)
	at com.github.kokorin.jaffree.ffprobe.data.DBase.getRatio(DBase.java:82)`

if (value != null && !value.isEmpty() && !value.equals("0/0")) may add the "N/A" judge

**Comment by kokorin** [comment]
Could you provide ffprobe output? Actually the message you provided is only a warning, the result is the same: null.

**Comment by kokorin** [comment]
Also you can implement your own converter and directly use methods of DBase subclasses:
`stream.getSection().getValue(key, yourOwnConverterToRatio)`

**Comment by msly** [comment]
not a warn, when use fastjson cast to string, JSON.toJSONString( stream );

**Comment by kokorin** [comment]
Did you include Fast JSON? Jaffree doesn't need it. Could you provide working sample with error?

**Comment by msly** [comment]
just for log info
use SerializerFeature.IgnoreErrorGetter sovled
`log.info(JSON.toJSONString(stream,` SerializerFeature.IgnoreErrorGetter));`
