### ISSUE TITLE
DBase logs warning when Display Aspect Ratio is not defined in probed result

### ISSUE THREAD

**Issue by jonfryd** [kokorin/Jaffree#40]
Hi @kokorin,

I've noticed that `DBase` logs the error below when I'm attempting to get a display aspect ratio which is not set for a particular video file. Would it make sense to make an explicit check for "N/A" and just return null before attempting to parse?

```
11:22:56.682 [main] WARN com.github.kokorin.jaffree.ffprobe.data.DBase - Failed to parse rational number: N/A
java.lang.NumberFormatException: For input string: "N/A"
	at com.github.kokorin.jaffree.Rational.valueOf(Rational.java:165)
	at com.github.kokorin.jaffree.ffprobe.data.DBase$RationalConverter.convert(DBase.java:158)
	at com.github.kokorin.jaffree.ffprobe.data.DBase$RationalConverter.convert(DBase.java:140)
	at com.github.kokorin.jaffree.ffprobe.data.DBase.getValue(DBase.java:44)
	at com.github.kokorin.jaffree.ffprobe.data.DBase.getRatio(DBase.java:82)
	at com.github.kokorin.jaffree.ffprobe.Stream.getDisplayAspectRatio(Stream.java:121)
```

I'm doing a `stream.getSection().getString("display_aspect_ratio").equalsIgnoreCase("N/A")` check in my own code for now, but IMO it would be nice if Jaffree handled this.

**Comment by kokorin** [comment]
Hi @jonfryd  

Thanks for your suggestion, will try to take a look this weekend. I will also be pleased to accept pull request.

**Comment by jonfryd** [comment]
Great! Thanks for improving this, @kokorin.
