### ISSUE TITLE
Can't convert audio only file (mp3)

### ISSUE THREAD

**Issue by Emmenemoi** [kokorin/Jaffree#44]
```
2019-03-28 07:48:07.564 WARN [FFmpeg-async-runner][] c.g.k.j.p.ProcessHandler - Waiting for process has been interrupted
java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:395)
	at com.github.kokorin.jaffree.process.ProcessHandler.interactWithProcess(ProcessHandler.java:112)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:85)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:161)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg$1.call(FFmpeg.java:176)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg$1.call(FFmpeg.java:173)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
2019-03-28 07:48:07.564 WARN [FFmpeg-async-runner][] c.g.k.j.p.Executor - Interrupting ALIVE thread: StdOut
```
Probably problem parsing ffmpeg output being (for audio only):
size=   11986kB time=00:24:55.80 bitrate=  65.6kbits/s speed=55.8x

**Comment by st-h** [comment]
@Emmenemoi I have been using Jaffree to convert and analyse audio files without issues. Usually you can get more information about what is going on by enabling debug logging. This also prints out the command being executed, which often is the cause of the error you are seeing.

You can also set a breakpoint here and see what command is executed https://github.com/kokorin/Jaffree/blob/b69f08e558dd5492c14e98202570ab9f197b73f5/src/main/java/com/github/kokorin/jaffree/process/ProcessHandler.java#L77

This is what I have added to my log4j config to enable logging
```
        {
          "name": "com.github.kokorin.jaffree",
          "level": "debug",
          "additivity": "false",
          "appender-ref": [
            {
              "ref": "File-Appender"
            }
          ]
        },
```

Hope that helps in finding the cause of your issue

**Comment by Emmenemoi** [comment]
Yes, sorry. After enabling debug logging i found the problem in the progress handler...

**Comment by kokorin** [comment]
@Emmenemoi  thanks for your interest in Jaffree. @st-h thanks for your help!
