### ISSUE TITLE
Getting error=13, Permission denied when using try to use the documented code

### ISSUE THREAD

**Issue by rameshvoltella** [kokorin/Jaffree#61]
Hi,

Am using this awsome library for ffmpeg in java,i use the documeted code in github and am getting the following issue.
Am using netbeans 8.2 in ubandu 16.04 also installed the ffmpeg in ubandu device can you tell me what to do?

```
t com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:87)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:161)
	at com.olakka.ffmpegchunker.ConvertionScreen.type2(ConvertionScreen.java:112)
	at com.olakka.ffmpegchunker.ConvertionScreen.jButton1ActionPerformed(ConvertionScreen.java:85)
	at com.olakka.ffmpegchunker.ConvertionScreen.access$000(ConvertionScreen.java:24)
	at com.olakka.ffmpegchunker.ConvertionScreen$1.actionPerformed(ConvertionScreen.java:50)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.IOException: Cannot run program "/home/olakka/Desktop/TestFroencfromubandu/ffmpeg_directory/ffmpeg": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:83)
	... 41 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 42 more
```

**Comment by kokorin** [comment]
Hello @rameshvoltella 
The log clearly says that it's permission problem: 

> Cannot run program "/home/olakka/Desktop/TestFroencfromubandu/ffmpeg_directory/ffmpeg": error=13, Permission denied

I would check rights of the user under which you run JVM. Try to execute any `ffmpeg` command under that user. Probably that user doesn't have execute permissions on ffmpeg

**Comment by rameshvoltella** [comment]
I run ffmpeg its workin

**Comment by rameshvoltella** [comment]
i run ffmpeg and i got the following result
```
ffmpeg -version
ffmpeg version 4.2.1-2~16.04.york1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
configuration: --prefix=/usr --extra-version='2~16.04.york1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-nonfree --enable-libfdk-aac --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

**Comment by rameshvoltella** [comment]
@kokorin what should i do?i know something wrong in my side what should do to fix this?

**Comment by rameshvoltella** [comment]
@kokorin i have executed the folloing command
`ffmpeg -i /home/olakka/Desktop/TestFroencfromubandu/neyback.mp4 -ss 00:00:00.000 -map_chapters -1 -c:v libx264 -c:a copy -crf 18 -t 00:03:52.292 /home/olakka/Desktop/TestFroencfromubandu/caaut.mp4`

Its execute i got the out put but when i using lib its not working

**Comment by kokorin** [comment]
@rameshvoltella 
execute in bash and give results here:
```
whoami
ls -lhtr /home/olakka/Desktop/TestFroencfromubandu/ffmpeg_directory/
/home/olakka/Desktop/TestFroencfromubandu/ffmpeg_directory/ffmpeg -v
```

And post result here

**Comment by rameshvoltella** [comment]
there is no ffmpeg_directory in my home folder

**Comment by rameshvoltella** [comment]
i followed the https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu link and made the ffmpeg_sources folder and executed the above command you given

> whoami
> ls -lhtr /home/oliveboard/ffmpeg_sources/
> /home/oliveboard/ffmpeg_sources/ffmpeg-v


total 11M
-rw-rw-r--  1 olakka olakka  11M Dec 23 22:54 ffmpeg-snapshot.tar.bz2
drwxrwxr-x 18 olakka olakka 4.0K Dec 24 11:11 aom
drwxrwxr-x  8 olakka olakka 4.0K Dec 24 11:20 aom_build
drwxr-xr-x 18 olakka olakka 4.0K Dec 24 11:54 ffmpeg

And when i try the **whereis ffmpeg** i get the following result
`ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /home/olakka/bin/ffmpeg /usr/share/man/man1/ffmpeg.1.gz`

So in the **Path BIN** as per doc which path i need to give i tried both but all path giving same issue

**Comment by rameshvoltella** [comment]
@kokorin 
Final i fixed it man i do the following
1)First i find where is my ffmpeg directory using following command
`whereis ffmpeg`
i got the following result with the path of ffmpeg
`ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /home/olakka/bin/ffmpeg /usr/share/man/man1/ffmpeg.1.gz`

After that i moved the **ffmpeg** from **usr** folder to home directory using following command

> sudo mv /path/file /destination/folder

in my case
`sudo mv /usr/bin/ffmpeg /home/olakka/ffmpeg_directory`
**ffmpeg_directory** is a i folder created to place the **ffmpeg** file from **usr** folder

After that i give access permission to ffmpeg using **chmod 775** using following command
`sudo chmod 775 /home/olakka/ffmpeg_directory/ffmpeg`

After that in the code of my application in the Path BIN i added the above directory address
Like this
`Path BIN = Paths.get("/home/olakka/ffmpeg_directory/");`
AND  EUREKA the code works this will help some one with this issue also @kokorin thank you for helping me to understand and fix the issue

also if you have trouble to find ffmpeg or ffmpeg is not installed correctly please refer the following sites
1)[https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-18-04/](https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-18-04/)
or
2)[https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu)

i recommend the step no 1 after that try to do the above steps and if step 1 fails then only go for the step 2.
Thank you

**Comment by kokorin** [comment]
@rameshvoltella if in your system ffmpeg is available via `PATH` environment variable you can make things easier: Jaffree can be ran  with `FFmpeg.atPath()`
