### ISSUE TITLE
No result + non zero status: 1

### ISSUE THREAD

**Issue by ZctrapCoding** [kokorin/Jaffree#9]
```
Caused by: java.lang.RuntimeException: Process has ended with no result and non zero status: 1
	at com.github.kokorin.jaffree.process.ProcessHandler.execute(ProcessHandler.java:220)
	at com.github.kokorin.jaffree.ffmpeg.FFmpeg.execute(FFmpeg.java:143)
	at commands.Commands.webToGifConv(Commands.java:61)
	at commands.Commands.gifInputStream(Commands.java:88)
	at commands.Commands.onGifCommand(Commands.java:129)
	... 11 common frames omitted
```
with the setttings of 
```
Path BIN = Paths.get("C:/ffmpeg/bin/");
		Path INPUT = Paths.get(path+"temp.webp");
		Path OUTPUT = Paths.get(path+"temp.gif");
		FFmpeg result = FFmpeg.atPath(BIN)
				.addInput(UrlInput.fromPath(INPUT))
				.addOutput(UrlOutput.toPath(OUTPUT)
						.setCodec(StreamType.VIDEO, "libx264"));
		result.execute();
```
I'm probably doing something incorrectly, which is pretty sstraightfoward, butt if anyonee could  help me i'd be nice.

**Comment by kokorin** [comment]
Hi, thanks for your interest to Jaffree.

First of all, 
> path+"temp.webp"

looks  suspicious. Ensure you have added path separator between folder and file.
 
If that won't help, than try to add slf4j-log4j12 binding to your classpath and add log4j.xml to resource folder. Check [this](https://github.com/kokorin/Jaffree/blob/master/examples/) for examples.

**Comment by kokorin** [comment]
Since 0.5.2 if error has been found, an exception is thrown
